### ISSUE TITLE
Error: EEXIST since NativeScript 2.4

### ISSUE THREAD

**Issue by csaggo** [rborn/nativescript-i18n#24]
After updating to NativeScript 2.4 i keep getting EEXIST errors like this one:
shell.js: internal error
Error: EEXIST: file already exists, symlink '../rimraf/bin.js' -> '/Users/mcsaki-mbp/ _ PATH TO APP TNS MODULE _ /tns_modules/nativescript-i18n/node_modules/fs-extra/node_modules/.bin/rimraf'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:1054:18)
    at cpdirSyncRecursive (/Users/mcsaki-mbp/.nvm/versions/v6.9.1/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:76:10)
    at cpdirSyncRecursive (/Users/mcsaki-mbp/.nvm/versions/v6.9.1/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:73:7)
    at cpdirSyncRecursive (/Users/mcsaki-mbp/.nvm/versions/v6.9.1/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:73:7)
    at cpdirSyncRecursive (/Users/mcsaki-mbp/.nvm/versions/v6.9.1/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:73:7)
    at cpdirSyncRecursive (/Users/mcsaki-mbp/.nvm/versions/v6.9.1/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:73:7)
    at /Users/mcsaki-mbp/.nvm/versions/v6.9.1/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:183:9
    at Array.forEach (native)
    at Object._cp (/Users/mcsaki-mbp/.nvm/versions/v6.9.1/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:157:11)
    at Object.cp (/Users/mcsaki-mbp/.nvm/versions/v6.9.1/lib/node_modules/nativescript/node_modules/shelljs/src/common.js:186:23)
    at TnsModulesCopy.copyDependencyDir (/Users/mcsaki-mbp/.nvm/versions/v6.9.1/lib/node_modules/nativescript/lib/tools/node-modules/node-modules-dest-copy.js:36:21)
    at TnsModulesCopy.copyModules (/Users/mcsaki-mbp/.nvm/versions/v6.9.1/lib/node_modules/nativescript/lib/tools/node-modules/node-modules-dest-copy.js:16:18)
    at /Users/mcsaki-mbp/.nvm/versions/v6.9.1/lib/node_modules/nativescript/lib/tools/node-modules/node-modules-builder.js:129:32
    at Function.settle (/Users/mcsaki-mbp/.nvm/versions/v6.9.1/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.wait (/Users/mcsaki-mbp/.nvm/versions/v6.9.1/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)

it only works the very first time. Solution for now is to delete hooks, platforms and node-modules and just make the livesync or run command for one platform. next time i have to do this again.
not sure if the issue is really with the plugin or ns 2.4 but plugin name fell in my eye.

**Comment by rborn** [comment]
Thank you, I'll try to have a look.

**Comment by thematan** [comment]
full solution should come from fixing the nativescript build process,
they copy all js files using shelljs and it fails when copying symlinks
WORKAROUND: delete 'rimraf' link from .bin directory
`rm node_modules/nativescript-i18n/node_modules/fs-extra/node_modules/.bin/rimraf`

**Comment by rborn** [comment]
@thematan thanks for finding this 👍
