### ISSUE TITLE
cannot prepare project

### ISSUE THREAD

**Issue by ghost** [rborn/nativescript-i18n#29]
@rborn I'm implementing a project to use #28 in, but if I run `tns prepare ios` more than once, the prepare crashes; the only solution right now is for me to manually delete that rimraf/bin.js

```js
Executing before-prepare hook from my.project.app/hooks/before-prepare/nativescript-i18n.js
shell.js: internal error
Error: EEXIST: file already exists, symlink '../rimraf/bin.js' -> 'my.project.app/platforms/ios/myprojectapp/app/tns_modules/nativescript-i18n/node_modules/fs-extra/node_modules/.bin/rimraf'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:897:18)
    at cpdirSyncRecursive (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:76:10)
    at cpdirSyncRecursive (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:73:7)
    at cpdirSyncRecursive (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:73:7)
    at cpdirSyncRecursive (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:73:7)
    at cpdirSyncRecursive (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:73:7)
    at /usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:183:9
    at Array.forEach (native)
    at Object._cp (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/cp.js:157:11)
    at Object.cp (/usr/local/lib/node_modules/nativescript/node_modules/shelljs/src/common.js:186:23)
    at TnsModulesCopy.copyDependencyDir (/usr/local/lib/node_modules/nativescript/lib/tools/node-modules/node-modules-dest-copy.js:42:21)
    at _loop_1 (/usr/local/lib/node_modules/nativescript/lib/tools/node-modules/node-modules-dest-copy.js:17:20)
    at TnsModulesCopy.copyModules (/usr/local/lib/node_modules/nativescript/lib/tools/node-modules/node-modules-dest-copy.js:31:13)
    at /usr/local/lib/node_modules/nativescript/lib/tools/node-modules/node-modules-builder.js:129:32
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26
```

Edit: This seems to be a duplicate of #24, but I am not having this issue with any other plugins.  Considering that a NS issue was fixed regarding this, I don't know exactly where this fits.

**Comment by rborn** [comment]
I'm away from the keyboard till January next year, so cannot do anything right now. 

Anyway, the offending part seems to be the fs-extra module in [before-prepare.js](https://github.com/rborn/nativescript-i18n/blob/master/lib/before-prepare.js). 
If you can't wait till I come back, you could replace it with the normal `fs` module and adjust the `ensureFile` part accordingly (and make a PR 😄 )
